### ISSUE TITLE
Broken blog link on homepage

### ISSUE THREAD

**Issue by dannysantino** [victoriacheng15/website#24]
The blog link on the homepage is broken and only leads to a 404 Errror page.

**Comment by victoriacheng15** [comment]
Hey @dannysantino!

[Thomas](https://www.linkedin.com/feed/update/urn:li:activity:6991418619268136962?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6991418619268136962%2C6991442079801311232%29) mentioned in the comment as well. 

Thank you for letting me know about this! 👍

**Comment by dannysantino** [comment]
Oh, all right, then.
