### ISSUE TITLE
Maybe "resources" should say "journals" instead?

### ISSUE THREAD

**Issue by TheAmazinRaven** [victoriacheng15/website#25]
I think you should change your "learning resources" page to "journal" as it is more reflective of you logging what you're learning on your journey. :) tehe

**Comment by victoriacheng15** [comment]
Hey @TheAmazinRaven!

Thank you for raising this issue. You have a point there. I kinda feel the same way as you say.

**Comment by TheAmazinRaven** [comment]
> Hey @TheAmazinRaven!
> 
> Thank you for raising this issue. You have a point there. I kinda feel the same way as you say.

No problem :D
